/**
 * Build the Brush trainer (Rust -> WASM) and place the artifacts where
 * VoluLab loads them.
 *
 * Source: the `volulab` branch of https://github.com/cyberhirsch/brush,
 * checked out at Repos/brush. Requires the Rust toolchain (1.95+), the
 * wasm32-unknown-unknown target and wasm-pack - which is why the built
 * artifacts under static/brush/pkg are committed: most machines touching
 * VoluLab have no Rust toolchain, and the trainer changes rarely.
 *
 * `--target web` is deliberate: the pkg is loaded at runtime through a
 * computed-URL dynamic import (see src/training/brush-engine.ts), so
 * rollup never has to understand wasm.
 */

import { execSync } from 'node:child_process';
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const crate = join(root, 'Repos', 'brush', 'apps', 'brush-js');
const outDir = join(crate, 'pkg-web');
const pkgDest = join(root, 'static', 'brush', 'pkg');
const dtsDest = join(root, 'src', 'training', 'brush-pkg.d.ts');

execSync('wasm-pack build --release --target web --out-dir pkg-web --out-name brush_js', {
    cwd: crate,
    stdio: 'inherit'
});

mkdirSync(pkgDest, { recursive: true });
copyFileSync(join(outDir, 'brush_js.js'), join(pkgDest, 'brush_js.js'));
copyFileSync(join(outDir, 'brush_js_bg.wasm'), join(pkgDest, 'brush_js_bg.wasm'));

// wrap the generated typings as an ambient module so the engine wrapper gets
// real types without rollup ever resolving 'brush-pkg' as an import
const raw = readFileSync(join(outDir, 'brush_js.d.ts'), 'utf8');
const dts = raw.split('\n').map(line => `    ${line}`).join('\n');
writeFileSync(dtsDest, `// Generated by scripts/build-brush.mjs - do not edit.\ndeclare module 'brush-pkg' {\n${dts}\n}\n`);

console.log(`brush pkg -> ${pkgDest}`);
console.log(`typings   -> ${dtsDest}`);
